USE_CAMERA_STUB := true
TARGET_NO_BOOTLOADER := true

TARGET_BOARD_PLATFORM := msm7x30
TARGET_BOARD_PLATFORM_GPU := qcom-adreno200

TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_SPECIFIC_HEADER_PATH := device/se/arc/include

BOARD_WPA_SUPPLICANT_DRIVER := CUSTOM
BOARD_WLAN_DEVICE := wl1271
BOARD_SOFTAP_DEVICE := wl1271
WPA_SUPPLICANT_VERSION := VER_0_6_X
WIFI_DRIVER_MODULE_PATH := /system/lib/modules/tiwlan_drv.ko
WIFI_DRIVER_MODULE_NAME := tiwlan_drv
WIFI_FIRMWARE_LOADER := wlan_loader
#WIFI_EXT_MODULE_PATH := /system/lib/modules/sdio.ko
#WIFI_EXT_MODULE_NAME := sdio

TARGET_BOOTLOADER_BOARD_NAME := mogami

BOARD_USES_GENERIC_AUDIO := false
#TARGET_PROVIDES_LIBAUDIO := true

#BOARD_USES_ALSA_AUDIO := true
#BOARD_USES_ALSA_UTILS := true
#BOARD_PREBUILT_LIBAUDIO := true

BOARD_HAVE_BLUETOOTH := true
#BOARD_HAVE_BLUETOOTH_BCM := true


BOARD_EGL_CFG := device/se/arc/prebuilt/egl.cfg

BOARD_USES_QCOM_LIBS := true
BOARD_USES_QCOM_LIBRPC := true
#BOARD_USES_QCOM_GPS := true
BOARD_USE_QCOM_PMEM := true

#TARGET_HAVE_HDMI_OUT := true
#TARGET_GRALLOC_USES_ASHMEM := true

#BOARD_CAMERA_USE_GETBUFFERINFO := true

#BOARD_OVERLAY_FORMAT_YCbCr_420_SP := true

BOARD_VENDOR_QCOM_AMSS_VERSION := 1240
BOARD_VENDOR_QCOM_GPS_LOC_API_HARDWARE := semc
BOARD_VENDOR_QCOM_GPS_LOC_API_AMSS_VERSION := 1240

# Current drivers don't support new EGL config
#BOARD_NO_RGBX_8888 := true

BOARD_HAVE_FM_RADIO := true
BOARD_GLOBAL_CFLAGS += -DHAVE_FM_RADIO

BOARD_HAS_NO_MISC_PARTITION := true
BOARD_USES_RECOVERY_CHARGEMODE := false

#BOARD_OVERLAY_MINIFICATION_LIMIT := 2

BOARD_KERNEL_CMDLINE := console=null
BOARD_KERNEL_BASE := 0x00200000

#TARGET_PROVIDES_LIBRIL := true
#BOARD_HAS_BGRA8888 := true
